Add retry logic around git commands

diff --git a/linux/functions b/linux/functions
--- a/linux/functions
+++ b/linux/functions
@@ -26,4 +26,26 @@ scheduleForNextRun() {
 	echo $1 > ${MY_HOME}/.onstart
 }
 
+failRetry() {
+	echo $1 >&2
+	exit 1
+}
+
+retry() {
+	local n=1
+	local max=5
+	local delay=15
+	while true; do
+		"$@" && break || {
+			if [[ $n -lt $max ]]; then
+				((n++))
+				echo "!!! Command failed. Attempt $n/$max: !!!"
+				sleep $delay;
+			else
+				fail "!!! The command has failed after $n attempts !!!"
+			fi
+		}
+	done
+}
+
 resetPermissions
